[PHP]
; Mengatasi error overflow 2G pada arsitektur WASM 32-bit
memory_limit = 128M
upload_max_filesize = 50M
post_max_size = 50M

; Keamanan tambahan
max_execution_time = 30
display_errors = Off
log_errors = On
